export const WEATHER_DETAILS_REQUEST = "WEATHER_DETAILS_REQUEST";
export const WEATHER_DETAILS_SUCCESS = "WEATHER_DETAILS_SUCCESS";
export const WEATHER_DETAILS_FAIL = "WEATHER_DETAILS_FAIL";
export const UPDATE_CITY = "UPDATE_CITY";
export const CREATE_METRICS_REQUEST = "CREATE_METRICS_REQUEST";
export const CREATE_METRICS_SUCCESS = "CREATE_METRICS_SUCCESS";
export const CREATE_METRICS_FAIL = "CREATE_METRICS_FAIL";
